-- 02_create_tables.sql
DROP TABLE IF EXISTS employees;
CREATE TABLE employees (
    "EmployeeID" TEXT,
    "Age" INTEGER,
    "AgeGroup" TEXT,
    "Gender" TEXT,
    "Department" TEXT,
    "JobRole" TEXT,
    "MonthlyIncome" INTEGER,
    "SalaryRange" TEXT,
    "YearsAtCompany" INTEGER,
    "TenureGroup" TEXT,
    "YearsInCurrentRole" INTEGER,
    "YearsWithCurrentManager" INTEGER,
    "YearsSinceLastPromotion" INTEGER,
    "Overtime" TEXT,
    "JobSatisfaction" INTEGER,
    "SatisfactionLabel" TEXT,
    "WorkLifeBalance" INTEGER,
    "JobLevel" INTEGER,
    "BusinessTravel" TEXT,
    "DistanceFromHome" REAL,
    "Education" INTEGER,
    "EducationField" TEXT,
    "MaritalStatus" TEXT,
    "MonthlyRate" INTEGER,
    "DailyRate" INTEGER,
    "HourlyRate" INTEGER,
    "EnvironmentSatisfaction" INTEGER,
    "RelationshipSatisfaction" INTEGER,
    "JobInvolvement" INTEGER,
    "StockOptionLevel" INTEGER,
    "TrainingTimesLastYear" INTEGER,
    "NumCompaniesWorked" INTEGER,
    "PerformanceRating" INTEGER,
    "Attrition" TEXT,
    "AttritionFlag" INTEGER,
    PRIMARY KEY (EmployeeID)
);
